name: Snitch Security Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
  security-events: write
  statuses: write
  models: read
jobs:
  snitch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: snitchplugin/snitch-github-action@sca-preview
        with:
          snitch-license-key: ${{ secrets.SNITCH_LICENSE_KEY }}
          trigger-mode: always
